---

- name: Install memcached
  apt: 
    name: memcached
    state: present
  notify:
    - enable memcached

- name: Setup configuration
  template:
    src: memcached.conf.j2
    dest: /etc/memcached.conf
  notify:
   - restart memcached
