---

- name: Install memcached
  apt: name=memcached state=present
  notify:
    - enabled memcache

- name: Copy conf to the machine
  template:
    src: templates/memcached.conf.j2
    dest: /etc/memcached.conf
  notify:
   - restart memcached